Get http://localhost:3000/users/get_student

########
POST http://localhost:3000/users/create_student

content-type: application/json

{
    "name": "musty",
    "other": "lala",
    "image": "jjdjd"
}